version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      timezone: 'Europe/Berlin'
      time: '21:00'
      day: friday
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: weekly
      timezone: 'Europe/Berlin'
      time: '21:00'
      day: friday
    commit-message:
      prefix: meta
    groups:
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
      testing-library:
        patterns:
          - '@testing-library/*'
          - '@types/testing-library*'
      next-js:
        patterns:
          - 'next'
          - 'turbo'
          - 'next-mdx-remote'
          - 'next-sitemap'
          - 'next-themes'
          - '@vercel/*'
      remark-mdx:
        patterns:
          - '@vcarl/remark-headings'
          - 'remark-gfm'
          - '@mdx-js/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
    open-pull-requests-limit: 10
