- import _ from 'lodash';
-
- function component() {
+ function getComponent() {
-   const element = document.createElement('div');
-
-   // Lodash, now imported by this script
-   element.innerHTML = _.join(['Hello', 'webpack'], ' ');
+   return import(/* webpackChunkName: "lodash" */ 'lodash').then(({ default: _ }) => {
+     const element = document.createElement('div');
+
+     element.innerHTML = _.join(['Hello', 'webpack'], ' ');
+
+     return element;
+
+   }).catch(error => 'An error occurred while loading the component');
  }

- document.body.appendChild(component());
+ getComponent().then(component => {
+   document.body.appendChild(component);
+ })files:
  - source: /locale/en/**/*.md
    translation: /locale/%two_letters_code%/**/%original_file_name%
    content_segmentation: 0
    languages_mapping:
      two_letters_code:
        pt-BR: pt-br
        zh-CN: zh-cn
        zh-TW: zh-tw
  - source: /locale/en/**/*.json
    translation: /locale/%two_letters_code%/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-br
        zh-CN: zh-cn
        zh-TW: zh-tw
