name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build for GitHub Pages
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install NPM packages
        run: npm ci

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Build Next.js
        run: npx turbo build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          NEXT_BASE_PATH: /nodejs.org

      - name: Export Next.js static files
        run: npx turbo export

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
