name: Pull Request Checks

on:
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install NPM packages
        run: npm ci

      - name: Run Linting
        run: npm run lint

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install NPM packages
        run: npm ci

      - name: Restore Next.js cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build Next.js
        run: npm run build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Save Next.js cache
        uses: actions/cache/save@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('.next/cache/eslint') }}
